version: "3.7"
services:
  elasticsearch:
    build:
      context: ./elasticsearch/
      args:
        IMAGE_VERSION: ${IMAGE_VERSION}
    container_name: es01
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    build:
      context: ./kibana/
      args:
        IMAGE_VERSION: ${IMAGE_VERSION}
    container_name: kibana01
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: ./logstash/
      args:
        IMAGE_VERSION: ${IMAGE_VERSION}
    container_name: logstash01

volumes:
  esdata01:
    driver: local
